# Generated by Django 5.1.5 on 2025-03-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatmap',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='heatmap',
            name='start_date',
        ),
    ]
