# Generated by Django 5.1.5 on 2025-03-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_heatmap_unique_together_remove_heatmap_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='habits.habit'),
        ),
    ]
