# Generated by Django 5.1.5 on 2025-03-12 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_heatmap_unique_together_remove_heatmap_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='user',
        ),
    ]
