# Generated by Django 5.1.5 on 2025-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habitentry_unique_together_habitentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='date',
            field=models.DateTimeField(blank=True, default='01/01/2000'),
        ),
    ]
