# Generated by Django 5.1.5 on 2025-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habitentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
