# Generated by Django 5.1.5 on 2025-03-12 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habitentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
