# Generated by Django 5.1.5 on 2025-04-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='habits/profile_pics/default.png', upload_to='habits/profile_pics'),
        ),
    ]
